### ISSUE TITLE
Speedwagon HathiPrep Error

### ISSUE THREAD

**Issue by vbjohna** [UIUCLibrary/Speedwagon#465]
Henry,
I tried to run Hathi Prep in Speedwagon.  Here is the information from speedwagon and a screenshot of the error. Would you let me know when this is fixed so I can run the things.
Let me know if you need anything else. - Johna

Traceback (most recent call last):
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\runner_strategies.py", line 649, in run_job_on_thread
    task.exec()
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\tasks\tasks.py", line 186, in exec
    TaskStatus.FAILED if not self.work() else TaskStatus.SUCCESS
                             ^^^^^^^^^^^
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\tasks\prep.py", line 35, in work
    package_builder.make_yaml(build_path=self.subtask_working_dir,
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\pyhathiprep\package_creater.py", line 147, in make_yaml
    self.generate_meta_yaml(self._source, build_path, title_page)
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\pyhathiprep\package_creater.py", line 77, in generate_meta_yaml
    yml = make_yml(
          ^^^^^^^^^
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\pyhathiprep\hathiyml.py", line 186, in make_yml
    builder.set_capture_date(value)
  File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\pyhathiprep\hathiyml.py", line 117, in set_capture_date
    capture_date = timezone.localize(date)
                   ^^^^^^^^^^^^^^^^^
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'

![image](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/1fa54a3a-3e1a-4aae-a634-d3a3d6bc43bc)

**Comment by henryborchers** [comment]
Can you provide me with a list of the Installed Python Packages on the version you have installed?

You can find them by selecting "System Information" from the "System" menu.

**Comment by henryborchers** [comment]
@vbjohna this looks like a change in some code that is included to handle time zones. If you can provide me with the list of Python Packages in the "System Information" I can see if I can replicate your issue.

**Comment by vbjohna** [comment]
I will be happy to look. You are always welcome to remote in.



Johna (JAW-nuh) Von Behrens, MSEd, MLIS, CA

[A button with "Hear my name" text for name playback in email signature]<https://www.name-coach.com/johna-vonbehrens>


My work day may look different than your work day. Please do not feel obligated to respond out of your normal working hours.



***@***.***?anonymous&ep=signature>             Book time to meet with ***@***.***?anonymous&ep=signature>


Library Specialist
Digitization Services
University of Illinois Library at Urbana-Champaign
Room 413
1408 W Gregory Drive
Urbana, IL 61801
https://www.library.illinois.edu/preservation/digitization-services/services-for-patrons/


[https://webtools.illinois.edu/webservices/js/ds/signature_logo.png]<https://urldefense.proofpoint.com/v2/url?u=http-3A__illinois.edu_&d=DwMGaQ&c=Y6HT0gyZH_Z4ZSRJdNYJeQ&r=ST1mZUAQCqhYfUqphXXXG5QLbvO7hWbuwrHMJ4iwmQQ&m=8sm6evsOxtPdD2s7kJR8dZlYJNnvexdFQD8lBkfvWhU&s=8Lx0xFPxTeU-KaJgvQqyVtSuCJIU8SgnKQrQF_23u1I&e=>

Under the Illinois Freedom of Information Act any written communication to or from university employees regarding university business is a public record and may be subject to public disclosure.
________________________________

**Comment by vbjohna** [comment]
Henry you will probably be better off to look yourself. I am not sure where this info is or what I am looking for.
[cid:895b63c3-5d7b-4295-8311-9c75cada1f91]



Johna (JAW-nuh) Von Behrens, MSEd, MLIS, CA

[A button with "Hear my name" text for name playback in email signature]<https://www.name-coach.com/johna-vonbehrens>


My work day may look different than your work day. Please do not feel obligated to respond out of your normal working hours.



***@***.***?anonymous&ep=signature>             Book time to meet with ***@***.***?anonymous&ep=signature>


Library Specialist
Digitization Services
University of Illinois Library at Urbana-Champaign
Room 413
1408 W Gregory Drive
Urbana, IL 61801
https://www.library.illinois.edu/preservation/digitization-services/services-for-patrons/


[https://webtools.illinois.edu/webservices/js/ds/signature_logo.png]<https://urldefense.proofpoint.com/v2/url?u=http-3A__illinois.edu_&d=DwMGaQ&c=Y6HT0gyZH_Z4ZSRJdNYJeQ&r=ST1mZUAQCqhYfUqphXXXG5QLbvO7hWbuwrHMJ4iwmQQ&m=8sm6evsOxtPdD2s7kJR8dZlYJNnvexdFQD8lBkfvWhU&s=8Lx0xFPxTeU-KaJgvQqyVtSuCJIU8SgnKQrQF_23u1I&e=>

Under the Illinois Freedom of Information Act any written communication to or from university employees regarding university business is a public record and may be subject to public disclosure.
________________________________
