### ISSUE TITLE
Getmarc server not set error when running Speedwagon Beta 0.3.0b5

### ISSUE THREAD

**Issue by vbjohna** [UIUCLibrary/Speedwagon#485]
[Monday 10:49 AM] Von Behrens, Johna (jaw-nuh)
How do I get the new beta for speedwagon?
[Monday 10:49 AM] Borchers, Henry Samuel
on windows?
[Monday 10:49 AM] Von Behrens, Johna (jaw-nuh)
yes
[Monday 10:50 AM] Von Behrens, Johna (jaw-nuh)
All I see is the version I have on Choclately

[Monday 10:50 AM] Borchers, Henry Samuel
open chocolatey and select the include all prerelease 
[Monday 10:50 AM] Borchers, Henry Samuel
it's something like that but not the exact same words
[Monday 10:51 AM] Von Behrens, Johna (jaw-nuh)
It says its installed

[Monday 10:52 AM] Borchers, Henry Samuel
and the version you see when you started speedwagon says otherwise?
[Monday 10:52 AM] Von Behrens, Johna (jaw-nuh)
 
 
[Monday 10:53 AM] Borchers, Henry Samuel
okay, do this. In Chocolatey, click "Reinstall" when you have the beta version up
[Monday 10:54 AM] Von Behrens, Johna (jaw-nuh)
 
 
[Monday 10:56 AM] Borchers, Henry Samuel
okay that's a good sign
[Monday 10:56 AM] Von Behrens, Johna (jaw-nuh)
Should I restart the computer?
[Monday 10:57 AM] Borchers, Henry Samuel
shouldn't have to
[Monday 10:57 AM] Von Behrens, Johna (jaw-nuh)
OK, it is now the beta version
[Monday 10:57 AM] Borchers, Henry Samuel
super
[Monday 10:51 AM] Borchers, Henry Samuel
does it say the beta is installed?
[Monday 10:51 AM] Von Behrens, Johna (jaw-nuh)
[
![MicrosoftTeams-image](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/611b7755-712e-4a03-9c52-e679cf5a8509)
](url)
 
[Monday 10:52 AM] Borchers, Henry Samuel
and the version you see when you started speedwagon says otherwise?

[Monday 10:52 AM] Von Behrens, Johna (jaw-nuh)
 
![MicrosoftTeams-image (1)](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/757e93f3-a958-40b2-ab3c-882a7af1af2a)

 
[Monday 10:53 AM] Borchers, Henry Samuel
okay, do this. In Chocolatey, click "Reinstall" when you have the beta version up

[Monday 10:54 AM] Von Behrens, Johna (jaw-nuh)
 
![MicrosoftTeams-image (2)](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/d9e5b902-ad43-477a-921c-c9cd12010d06)

 
[Monday 10:56 AM] Borchers, Henry Samuel
okay that's a good sign
[Monday 10:56 AM] Von Behrens, Johna (jaw-nuh)
Should I restart the computer?
[Monday 10:57 AM] Borchers, Henry Samuel
shouldn't have to
[Monday 10:57 AM] Von Behrens, Johna (jaw-nuh)
OK, it is now the beta version
[Monday 10:57 AM] Borchers, Henry Samuel
super
 [Monday 10:57 AM] Von Behrens, Johna (jaw-nuh)
 
![MicrosoftTeams-image (3)](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/2d07d77c-21da-4779-9d85-e18a2f6f93cf)

 
[Monday 10:57 AM] Borchers, Henry Samuel
yayayay, let me know if you have any problems with this. I'd like to move forward with this to bring this out of beta

**Comment by vbjohna** [comment]
[Tuesday 7:21 AM] Von Behrens, Johna (jaw-nuh)
 
![MicrosoftTeams-image (5)](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/e1128d01-e133-4901-9497-84a59b600264)

 
Traceback (most recent call last):
File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\runner_strategies.py", line 679, in run_job_on_thread
for task in task_scheduler.iter_tasks(
File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\runner_strategies.py", line 524, in iter_tasks
yield from self.task_generator_strategy.iterate_tasks(
File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\runner_strategies.py", line 461, in iterate_tasks
for task in task_generator.tasks():
File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\runner_strategies.py", line 161, in tasks
for task in self.get_main_tasks(
File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\runner_strategies.py", line 194, in get_main_tasks
self.workflow.discover_task_metadata(
File "C:\ProgramData\chocolatey\lib\speedwagon\tools\venv\Lib\site-packages\speedwagon\workflows\workflow_get_marc.py", line 145, in discover_task_metadata
raise MissingConfiguration("Getmarc server url is not set")
speedwagon.exceptions.MissingConfiguration: Getmarc server url is not set
 
[Tuesday 7:22 AM] Von Behrens, Johna (jaw-nuh)
I got this error trying to run the Generate MARC.XML Files
[Tuesday 9:12 AM] Borchers, Henry Samuel
ok, it looks like you need to configure the getmarc server, it's in the settings
[Tuesday 9:16 AM] Borchers, Henry Samuel
[Configuration](onenote:https://uillinoisedu.sharepoint.com/sites/Speedwagon/SiteAssets/Speedwagon%20Notebook/General.one#Configuration&section-id=a745a153-ea3f-4b6e-8f16-9163bfe64932&page-id=f8e5f0d7-e770-4434-88cb-6b17081de879&end)  ([Web view](https://uillinoisedu.sharepoint.com/sites/Speedwagon/_layouts/15/Doc.aspx?sourcedoc=%7Bdb9d28d1-81c5-4d35-98ef-af194ead88b1%7D&action=edit&wd=target%28General.one%7C4d57d545-e57c-44aa-ad80-98ac401370a7%2FConfiguration%7Cf8e5f0d7-e770-4434-88cb-6b17081de879%2F%29&wdorigin=703&wdpreservelink=1))
[Tuesday 9:37 AM] Von Behrens, Johna (jaw-nuh)
I do not know how to do this.

![MicrosoftTeams-image (6)](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/560e5bb6-85ce-4a31-8af2-cb641f5234e8)
![MicrosoftTeams-image (7)](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/c0fcf1c3-7938-47a3-93ef-18005eccaba3)

[Tuesday 11:28 AM] Von Behrens, Johna (jaw-nuh)
I was wrong. Speedwagon did throw an error.
[Tuesday 11:28 AM] Borchers, Henry Samuel
oh
[Tuesday 11:28 AM] Von Behrens, Johna (jaw-nuh)
 
![MicrosoftTeams-image (8)](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/8d781906-99e3-4568-96be-ab0cddc4a269)

 
[Tuesday 11:28 AM] Borchers, Henry Samuel
hmmm....
[Tuesday 11:29 AM] Von Behrens, Johna (jaw-nuh)
I am kinda scared to ask. I allready piss them off on a monthly basis.
[Tuesday 11:31 AM] Borchers, Henry Samuel
can you open your setting window in Speedwagon and click on a button at the bottom that reads "Open Config file Directory"
[Tuesday 11:32 AM] Borchers, Henry Samuel
it's the same window you used to set getmarc server url
[Tuesday 11:31 AM] Borchers, Henry Samuel
can you open your setting window in Speedwagon and click on a button at the bottom that reads "Open Config file Directory"
[Tuesday 11:32 AM] Borchers, Henry Samuel
it's the same window you used to set getmarc server url
![MicrosoftTeams-image (9)](https://github.com/UIUCLibrary/Speedwagon/assets/144837926/c0edc80a-d78f-4b8c-8cd1-fe2f31cf93e5)
[Tuesday 11:32 AM] Borchers, Henry Samuel
super
[Tuesday 11:32 AM] Borchers, Henry Samuel
can you send me the workflow_settings.yml file. 
[Tuesday 11:32 AM] Borchers, Henry Samuel
you can drag and drop it here
[Tuesday 11:33 AM] Von Behrens, Johna (jaw-nuh)
[workflows_settings.yml](https://uillinoisedu-my.sharepoint.com/personal/johnav_illinois_edu/Documents/Microsoft%20Teams%20Chat%20Files/workflows_settings.yml)

[Tuesday 11:34 AM] Borchers, Henry Samuel
that should be correct
[Tuesday 11:35 AM] Borchers, Henry Samuel
what files are you trying to run this on?
[Tuesday 11:37 AM] Von Behrens, Johna (jaw-nuh)
U:\HTIngest\20230912_RBML_Cavagna_ar\99865373812205899
[Tuesday 11:38 AM] Borchers, Henry Samuel
ok I'll see if I can reproduce this error
[Tuesday 11:46 AM] Borchers, Henry Samuel
did you use "U:\HTIngest\20230912_RBML_Cavagna_ar\99865373812205899" or "U:\HTIngest\20230912_RBML_Cavagna_ar" for the input?
[Tuesday 11:46 AM] Von Behrens, Johna (jaw-nuh)
U:\HTIngest\20230912_RBML_Cavagna_ar\99865373812205899
[Tuesday 11:46 AM] Borchers, Henry Samuel
try "U:\HTIngest\20230912_RBML_Cavagna_ar"
[Tuesday 11:49 AM] Von Behrens, Johna (jaw-nuh)
That worked.
[Tuesday 11:49 AM] Borchers, Henry Samuel
I'm making a better error message in case that happens again. Thanks

**Comment by waarala2** [comment]
@henryborchers I confirmed that the Zip Packages script works .  That was the last one to confirm.  HT has accepted and published an item for us in HT.  It appears the this version and scripts of the beta are working for all our HT and DL packaging scripts HOWEVER - I am logging a separate ticket to describe the issues with the Medusa Preingest Curation script that is not working right.
