### ISSUE TITLE
Medusa Preingest Curation not properly deleting CaptureOne files

### ISSUE THREAD

**Issue by waarala2** [UIUCLibrary/Speedwagon#488]
The Medusa Preingest Curation is not working properly. Johna and Angela tested the script on Mac and Windows. The expected out come is for Speedwagon to do the following: -  Locates and deletes .DS_Store files, Locates and deletes Thumbs.db files, Locates and deletes Capture One files

The following files were deleted successfully: 
-  Locates and deletes .DS_Store files
-  Locates and deletes Thumbs.db files

The CaptureOne folder was not deleted however the contents of the folder and itd enclosed files were deleted.  

See attached document with Johna and Angela's feedback notes, error readout from Speedwagon and screenshots.
[Preingest-curation-step-error.docx](https://github.com/UIUCLibrary/Speedwagon/files/13549752/Preingest-curation-step-error.docx)

**Comment by henryborchers** [comment]
It looks like speedwagon is trying deleting folder that still has data in it. Making sure the files are deleted before removing the directory might do the trick

**Comment by henryborchers** [comment]
Can someone comment on if this was fixed in 0.3.0b7?

**Comment by henryborchers** [comment]
#500 should address this.

**Comment by waarala2** [comment]
> It looks like speedwagon is trying deleting folder that still has data in it. Making sure the files are deleted before removing the directory might do the trick

@henryborchers do you mean we have to delete files bfore your script will delete the folder? Can speedwagon delete the enclosed files?  If so i can share the file types?
