### ISSUE TITLE
speedwagon 0.3.0b5 errors

### ISSUE THREAD

**Issue by waarala2** [UIUCLibrary/Speedwagon#493]
I tested speedwagon 0.3.0b5 fully today.  I am listing the issues by script or action below. I am also attaching a document with details and screen shots.
Errors
[20231206-Speedwagon-Beta-Feedback.docx](https://github.com/UIUCLibrary/Speedwagon/files/13592857/20231206-Speedwagon-Beta-Feedback.docx)

- Generate MARC.XML Files - Speedwagon immediately closes
- Medusa PreIngest Curation - deletes files but non CaptureOne folders or enclosed forders
- Export Job for Generate MARC.XML– Tried to export job.  When I tried Export details, and click Save, I can’t, so I click cancel and get a prompt “Saving data failed”. I have to click cancel.  EXPORT JOB - Convert Capture One TIFF to Digital Library Compound Object and HathiTrust.  Error prompt says Speedwagon has exited due to an unhandled exception.  When I tried to export details and save the details, Speedwagon crashes and gives the Saving data failed error. I cant save the details.  I get the same results whever I try to export the job log.
- When I go to System, and Save to File, I get Speedwagon has exited due to an unhandled exception. Read only files system
- I tried to go to Preferences and got this prompt. Speedwagon has exited due to an unhandled exception. I clicked close and the program closes.
- When I go to Export Log –I get a Saving Log Failed,  when I click ok, a prompt to Export log appears, but I cannot save the log. I get this prompt again.I have to click cancel, then Speedwagon closes.

**Comment by henryborchers** [comment]
This was addressed elsewhere. I'm going to close this
