### ISSUE TITLE
Speedwagon 0.3.0b8 Testing

### ISSUE THREAD

**Issue by vbjohna** [UIUCLibrary/Speedwagon#505]
Attached is the Word doc to the testing. It looks like I had only one issue. I had forgotten to run the pre-curation process in one of the sessions. I was not able to go back and run it on the files after. 

You can find all the documentation here (Git Hub doesn't like json files): \\digitize\speedwagon-henry\Windows-Tests-Johna\JobExport

[Windows-Tests-Johna_Documentation.docx](https://github.com/UIUCLibrary/Speedwagon/files/13640104/Windows-Tests-Johna_Documentation.docx)

**Comment by henryborchers** [comment]
This was addressed elsewhere. I'm going to close this
